- name: 'First playbook'
  hosts: localhost
  remote_user: Mariauser
  become: true
  vars_files:
    - ./vars/00_vars.yaml

  tasks:
    - name: 'Instalación Podman, openssl y httpd-tools'
      yum:
        name: "{{ rpms }}"
        state: latest

    - name: Crear directorio /etc/ssl/csr
      file:
        path: /etc/ssl/csr
        state: directory
        mode: '0755'

    - name: Crear archivo de solicitud de certificado
      file:
        path: /etc/ssl/csr/ansible.com.csr
        state: touch
        mode: '0644'

    - name: Generar certificado 509
      community.crypto.x509_certificate:
        path: /etc/ssl/crt/ansible.com.crt
        privatekey_path: /etc/ssl/private/ansible.com.pem
        csr_path: /etc/ssl/csr/ansible.com.csr
        provider: selfsigned

    - name: Creacion de la imagen de contenedor
      containers.podman.podman_image:
        name: myimagen
        path: /Caso2Azure/podman
       # push: true

    - name: Subir imagen a Azure Container Registry
      shell: 'podman push mariaregistry.azurecr.io/myimagen'

