---
- name: 'First playbook'
  hosts: webservers
  remote_user: Mariauser
  become: true
  vars_files:
    - vars/00_vars.yaml

  tasks:
    - name: 'Instalación Podman, openssl y httpd-tools'
      yum:
        name: "{{ rpms }}"
        state: latest

    - name: 'login podman'
      containers.podman.podman_login:
        username: MariaRegistry
        password: 'KxYOCFIWn9Dsx+GfEotj2xauKLmfko6+eJhuP28VKE+ACRDDwrt4'
   
    - name: 'Creación de la imagen de contenedor'
      containers.podman.podman_image:
        name: myimagen
        path: /Caso2Azure/podman/Containerfile
        push: true

    - name: 'Accedo al ACR con las credenciales'
      shell: 'az acr get-credentials --resource-group rg-maria --name MariaRegistry --overwrite-existing'

    - name: 'Subir imagen a Azure Container Registry'
      shell: 'podman push mariaregistry.azurecr.io/myimagen'

    - name: 'Inicio del contenedor'
      containers.podman.podman_container:
        name: MariaRegistry
        image: myimagen
        state: started
        restart: true
        etc_hosts:
          other: webservers
        restart_policy: "no"
        ports:
          - "8080:8080"
          - webservers
        env:
          usuario: "maria"
          password: "maria"

