---
- name: 'Descarga imagenes del ARC'
  hosts: webservers
  remote_user: Mariauser
  become: true
  vars_files:
    - ./vars/00_vars.yaml

  tasks:
#    - name: 'Accedo al ACR con las credenciales'
 #     shell: 'az acr get-credentials  --resource-group rg-maria --name MariaRegistry'
 
    - name: 'Login podman'
      containers.podman.podman_login:
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
 
    - name: 'run container'
      containers.podman.podman_container:
       name: contenedor
       image: localhost/myimagen
       state: started

#    - name: 'bajar la imagen del ACR'
 #     containers.podman.podman_images:
  #     name: /var/lib/containers/storage/myimagen

    - name: Verificar los contenedores en ejecución
      command: podman ps
   
    - name: Verificar el estado del servidor web
      uri:
         url: http://10.88.0.4:8080
         return_content: yes
      register: response

    - name: Mostrar el estado del servidor web
      debug:
        msg: "El estado del servidor web es: {{ response.status }}"

